//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NateW.Ssm.ApplicationUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CarPC {
            get {
                return ((bool)(this["CarPC"]));
            }
            set {
                this["CarPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowLeft {
            get {
                return ((int)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowTop {
            get {
                return ((int)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mock ECU")]
        public string SsmPort {
            get {
                return ((string)(this["SsmPort"]));
            }
            set {
                this["SsmPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P58,AFR")]
        public string Main1 {
            get {
                return ((string)(this["Main1"]));
            }
            set {
                this["Main1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P12,g/s")]
        public string Main2 {
            get {
                return ((string)(this["Main2"]));
            }
            set {
                this["Main2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P200,g/rev")]
        public string Main3 {
            get {
                return ((string)(this["Main3"]));
            }
            set {
                this["Main3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P25,psi")]
        public string Main4 {
            get {
                return ((string)(this["Main4"]));
            }
            set {
                this["Main4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P79,F")]
        public string Main5 {
            get {
                return ((string)(this["Main5"]));
            }
            set {
                this["Main5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P11,F")]
        public string Main6 {
            get {
                return ((string)(this["Main6"]));
            }
            set {
                this["Main6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E44,%")]
        public string FTrim1 {
            get {
                return ((string)(this["FTrim1"]));
            }
            set {
                this["FTrim1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E45,%")]
        public string FTrim2 {
            get {
                return ((string)(this["FTrim2"]));
            }
            set {
                this["FTrim2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P12,g/s")]
        public string FTrim3 {
            get {
                return ((string)(this["FTrim3"]));
            }
            set {
                this["FTrim3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E46,%")]
        public string FTrim4 {
            get {
                return ((string)(this["FTrim4"]));
            }
            set {
                this["FTrim4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E47,%")]
        public string FTrim5 {
            get {
                return ((string)(this["FTrim5"]));
            }
            set {
                this["FTrim5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P3,%")]
        public string FTrim6 {
            get {
                return ((string)(this["FTrim6"]));
            }
            set {
                this["FTrim6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P10,degrees")]
        public string Timing1 {
            get {
                return ((string)(this["Timing1"]));
            }
            set {
                this["Timing1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E53,degrees")]
        public string Timing2 {
            get {
                return ((string)(this["Timing2"]));
            }
            set {
                this["Timing2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E40,degrees")]
        public string Timing3 {
            get {
                return ((string)(this["Timing3"]));
            }
            set {
                this["Timing3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E94,degrees")]
        public string Timing4 {
            get {
                return ((string)(this["Timing4"]));
            }
            set {
                this["Timing4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E95,degrees")]
        public string Timing5 {
            get {
                return ((string)(this["Timing5"]));
            }
            set {
                this["Timing5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E31,multiplier")]
        public string Timing6 {
            get {
                return ((string)(this["Timing6"]));
            }
            set {
                this["Timing6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E90,psi relative sea level")]
        public string Boost1 {
            get {
                return ((string)(this["Boost1"]));
            }
            set {
                this["Boost1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E35,psi")]
        public string Boost2 {
            get {
                return ((string)(this["Boost2"]));
            }
            set {
                this["Boost2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P36,%")]
        public string Boost3 {
            get {
                return ((string)(this["Boost3"]));
            }
            set {
                this["Boost3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P25,psi")]
        public string Boost4 {
            get {
                return ((string)(this["Boost4"]));
            }
            set {
                this["Boost4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E79,absolute %")]
        public string Boost5 {
            get {
                return ((string)(this["Boost5"]));
            }
            set {
                this["Boost5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E80,absolute %")]
        public string Boost6 {
            get {
                return ((string)(this["Boost6"]));
            }
            set {
                this["Boost6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P63,misfire count")]
        public string Roughness1 {
            get {
                return ((string)(this["Roughness1"]));
            }
            set {
                this["Roughness1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P64,misfire count")]
        public string Roughness2 {
            get {
                return ((string)(this["Roughness2"]));
            }
            set {
                this["Roughness2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P2,F")]
        public string Roughness3 {
            get {
                return ((string)(this["Roughness3"]));
            }
            set {
                this["Roughness3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P69,misfire count")]
        public string Roughness4 {
            get {
                return ((string)(this["Roughness4"]));
            }
            set {
                this["Roughness4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P70,misfire count")]
        public string Roughness5 {
            get {
                return ((string)(this["Roughness5"]));
            }
            set {
                this["Roughness5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P8,rpm")]
        public string Roughness6 {
            get {
                return ((string)(this["Roughness6"]));
            }
            set {
                this["Roughness6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P30,%")]
        public string A1 {
            get {
                return ((string)(this["A1"]));
            }
            set {
                this["A1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E84,estimated AFR")]
        public string A2 {
            get {
                return ((string)(this["A2"]));
            }
            set {
                this["A2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P47,%")]
        public string A3 {
            get {
                return ((string)(this["A3"]));
            }
            set {
                this["A3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E93,%")]
        public string A4 {
            get {
                return ((string)(this["A4"]));
            }
            set {
                this["A4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P58,AFR")]
        public string A5 {
            get {
                return ((string)(this["A5"]));
            }
            set {
                this["A5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P201,%")]
        public string A6 {
            get {
                return ((string)(this["A6"]));
            }
            set {
                this["A6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P49,degrees")]
        public string B1 {
            get {
                return ((string)(this["B1"]));
            }
            set {
                this["B1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P48,degrees")]
        public string B2 {
            get {
                return ((string)(this["B2"]));
            }
            set {
                this["B2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P8,rpm")]
        public string B3 {
            get {
                return ((string)(this["B3"]));
            }
            set {
                this["B3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P40,V")]
        public string B4 {
            get {
                return ((string)(this["B4"]));
            }
            set {
                this["B4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P39,V")]
        public string B5 {
            get {
                return ((string)(this["B5"]));
            }
            set {
                this["B5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P200,g/rev")]
        public string B6 {
            get {
                return ((string)(this["B6"]));
            }
            set {
                this["B6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7000")]
        public int MaxRpm {
            get {
                return ((int)(this["MaxRpm"]));
            }
            set {
                this["MaxRpm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("275")]
        public int MaxMafGS {
            get {
                return ((int)(this["MaxMafGS"]));
            }
            set {
                this["MaxMafGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public double MaxAbsoluteBoostBar {
            get {
                return ((double)(this["MaxAbsoluteBoostBar"]));
            }
            set {
                this["MaxAbsoluteBoostBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public double MaxLoadGRev {
            get {
                return ((double)(this["MaxLoadGRev"]));
            }
            set {
                this["MaxLoadGRev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0000FF")]
        public string ColorNormalButtonTop {
            get {
                return ((string)(this["ColorNormalButtonTop"]));
            }
            set {
                this["ColorNormalButtonTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000040")]
        public string ColorNormalButtonBottom {
            get {
                return ((string)(this["ColorNormalButtonBottom"]));
            }
            set {
                this["ColorNormalButtonBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#808080")]
        public string ColorNormalButtonText {
            get {
                return ((string)(this["ColorNormalButtonText"]));
            }
            set {
                this["ColorNormalButtonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#8080FF")]
        public string ColorSelectedButtonTop {
            get {
                return ((string)(this["ColorSelectedButtonTop"]));
            }
            set {
                this["ColorSelectedButtonTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000080")]
        public string ColorSelectedButtonBottom {
            get {
                return ((string)(this["ColorSelectedButtonBottom"]));
            }
            set {
                this["ColorSelectedButtonBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ColorSelectedButtonText {
            get {
                return ((string)(this["ColorSelectedButtonText"]));
            }
            set {
                this["ColorSelectedButtonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorLinesBetweenButtons {
            get {
                return ((string)(this["ColorLinesBetweenButtons"]));
            }
            set {
                this["ColorLinesBetweenButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ColorSixPackMajorText {
            get {
                return ((string)(this["ColorSixPackMajorText"]));
            }
            set {
                this["ColorSixPackMajorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#808080")]
        public string ColorSixPackMinorText {
            get {
                return ((string)(this["ColorSixPackMinorText"]));
            }
            set {
                this["ColorSixPackMinorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ColorSixPackHorizontalLine {
            get {
                return ((string)(this["ColorSixPackHorizontalLine"]));
            }
            set {
                this["ColorSixPackHorizontalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#808080")]
        public string ColorSixPackVerticalLines {
            get {
                return ((string)(this["ColorSixPackVerticalLines"]));
            }
            set {
                this["ColorSixPackVerticalLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorScatterPlotForeground {
            get {
                return ((string)(this["ColorScatterPlotForeground"]));
            }
            set {
                this["ColorScatterPlotForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorScatterPlotHighlightInner {
            get {
                return ((string)(this["ColorScatterPlotHighlightInner"]));
            }
            set {
                this["ColorScatterPlotHighlightInner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorScatterPlotHighlightOuter {
            get {
                return ((string)(this["ColorScatterPlotHighlightOuter"]));
            }
            set {
                this["ColorScatterPlotHighlightOuter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffff00")]
        public string ColorScatterPlotText {
            get {
                return ((string)(this["ColorScatterPlotText"]));
            }
            set {
                this["ColorScatterPlotText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ColorCommonBackground {
            get {
                return ((string)(this["ColorCommonBackground"]));
            }
            set {
                this["ColorCommonBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorCommonAxisLines {
            get {
                return ((string)(this["ColorCommonAxisLines"]));
            }
            set {
                this["ColorCommonAxisLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorCommonAxisText {
            get {
                return ((string)(this["ColorCommonAxisText"]));
            }
            set {
                this["ColorCommonAxisText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000080")]
        public string ColorCommonAxisHighlight {
            get {
                return ((string)(this["ColorCommonAxisHighlight"]));
            }
            set {
                this["ColorCommonAxisHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0000FF")]
        public string ColorHeatMapForeground {
            get {
                return ((string)(this["ColorHeatMapForeground"]));
            }
            set {
                this["ColorHeatMapForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ff0000")]
        public string ColorHeatMapHighlight {
            get {
                return ((string)(this["ColorHeatMapHighlight"]));
            }
            set {
                this["ColorHeatMapHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string ColorHeatMapCellText {
            get {
                return ((string)(this["ColorHeatMapCellText"]));
            }
            set {
                this["ColorHeatMapCellText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffff00")]
        public string ColorHeatMapOverlayText {
            get {
                return ((string)(this["ColorHeatMapOverlayText"]));
            }
            set {
                this["ColorHeatMapOverlayText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimize")]
        public string BackButton {
            get {
                return ((string)(this["BackButton"]));
            }
            set {
                this["BackButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlxPort {
            get {
                return ((string)(this["PlxPort"]));
            }
            set {
                this["PlxPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P58,AFR")]
        public string ParameterActualAfr {
            get {
                return ((string)(this["ParameterActualAfr"]));
            }
            set {
                this["ParameterActualAfr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P12,g/s")]
        public string ParameterMaf {
            get {
                return ((string)(this["ParameterMaf"]));
            }
            set {
                this["ParameterMaf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E84,estimated AFR")]
        public string ParameterDesiredAfr {
            get {
                return ((string)(this["ParameterDesiredAfr"]));
            }
            set {
                this["ParameterDesiredAfr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P8,rpm")]
        public string ParameterRpm {
            get {
                return ((string)(this["ParameterRpm"]));
            }
            set {
                this["ParameterRpm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P13,%")]
        public string ParameterThrottle {
            get {
                return ((string)(this["ParameterThrottle"]));
            }
            set {
                this["ParameterThrottle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P25,psi")]
        public string ParameterMrp {
            get {
                return ((string)(this["ParameterMrp"]));
            }
            set {
                this["ParameterMrp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P200,g/rev")]
        public string ParameterLoad {
            get {
                return ((string)(this["ParameterLoad"]));
            }
            set {
                this["ParameterLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P7,bar")]
        public string ParameterMap {
            get {
                return ((string)(this["ParameterMap"]));
            }
            set {
                this["ParameterMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E114,count")]
        public string ParameterKnockSum {
            get {
                return ((string)(this["ParameterKnockSum"]));
            }
            set {
                this["ParameterKnockSum"] = value;
            }
        }
    }
}
